HOMEPAGE_VAR_HOMEASSISTANT_URL: 
HOMEPAGE_VAR_ESPHOME_URL: 
HOMEPAGE_VAR_PFSENSE_URL: 
HOMEPAGE_VAR_VAULTWARDEN_URL: 
HOMEPAGE_VAR_PORTAINER_URL: 
HOMEPAGE_VAR_PORTAINER_KEY: 
HOMEPAGE_VAR_DUPLICATI_URL: 
HOMEPAGE_VAR_UPTIMEKUMA_URL: 
HOMEPAGE_VAR_UPTIMEKUMA_SLUG: 
HOMEPAGE_VAR_GLANCES_URL: 
HOMEPAGE_VAR_DOZZLE_URL: 
HOMEPAGE_VAR_OMADA_URL: 
HOMEPAGE_VAR_GOTIFY_URL: 
HOMEPAGE_VAR_GOTIFY_KEY: 
HOMEPAGE_VAR_JELLYFIN_URL: 
HOMEPAGE_VAR_JELLYFIN_KEY: 
HOMEPAGE_VAR_PORTAINER_VPS_URL: 
HOMEPAGE_VAR_PORTAINER_VPS_KEY: ""
HOMEPAGE_VAR_ADMINER_URL: 
HOMEPAGE_VAR_OPENWEATHERMAP_KEY: 