---
{{ if .Values.enableConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  services.yaml: ""
  settings.yaml: ""
  widgets.yaml:  ""
  custom.css: ""
  custom.js: ""
{{ end }}
