---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homepage.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
    # type: RollingUpdate
  selector:
    matchLabels:
      {{- include "homepage.selectorLabels" . | nindent 6 }}
      # app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        #  app.kubernetes.io/name: homepage
        {{- include "homepage.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "homepage.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      containers:
        - name: {{ include "homepage.fullname" . }}
          image: {{ .Values.image.repository}}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
