---
{{ if .Values.enableIngressRoute }}
{{- $fullName := include "homepage.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  tls:
    secretName: {{.Values.ingressRoute.tls.secretName}}

  routes:
    {{- range .Values.ingressRoute.rules }}
    - kind: Rule
      match: Host("{{ .host }}")
      services:
        - kind: Service
          name: {{ $fullName }}
          port: 3000
          sticky:
            cookie:
              httpOnly: true
              secure: true
              sameSite: none
    {{- end}}

{{ end }}
